import User from '../models/Users';

const samples: User[] = [
  {
    id: '1',
    name: '本田 大志',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-1.png',
    location: '栃木県',
    league: 'S',
    ranking: 1,
    score: 80,
    putt: 30,
    career: 5,
  },
  {
    id: '2',
    name: 'タイラー・キール',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-2.png',
    location: '東京都',
    league: 'S',
    ranking: 2,
    score: 82,
    putt: 32,
    career: 1,
  },
  {
    id: '3',
    name: '宮﨑 麻生',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-3.png',
    location: '神奈川県',
    league: 'S',
    ranking: 3,
    score: 82,
    putt: 36,
    career: 2,
  },
  {
    id: '4',
    name: '鍵 展子',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-4.png',
    location: '東京都',
    league: 'S',
    ranking: 4,
    score: 86,
    putt: 40,
    career: 6,
  },
  {
    id: '5',
    name: '唐澤 光',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-5.png',
    location: '埼玉県',
    league: 'A',
    ranking: 5,
    score: 87,
    putt: 37,
    career: 5,
  },
  {
    id: '6',
    name: '善波',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-6.jpg',
    location: '北海道',
    league: 'A',
    ranking: 6,
    score: 91,
    putt: 40,
    career: 3,
  },
  {
    id: '7',
    name: '大輪 俊弥',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-7.png',
    location: '宮城県',
    league: 'A',
    ranking: 7,
    score: 98,
    putt: 42,
    career: 7,
  },
  {
    id: '8',
    name: '三田地',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-8.png',
    location: '山梨県',
    league: 'A',
    ranking: 8,
    score: 101,
    putt: 41,
    career: 2,
  },
  {
    id: '9',
    name: 'ストーン',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-9.png',
    location: '福岡県',
    league: 'B',
    ranking: 9,
    score: 103,
    putt: 40,
    career: 8,
  },
  {
    id: '10',
    name: 'エステファン',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-10.png',
    location: '大阪府',
    league: 'B',
    ranking: 10,
    score: 110,
    putt: 44,
    career: 2,
  },
  {
    id: '11',
    name: 'ピアマン',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-11.png',
    location: '京都府',
    league: 'B',
    ranking: 11,
    score: 112,
    putt: 46,
    career: 1,
  },
  {
    id: '12',
    name: 'マーキーフ・アクレス',
    comment: 'よろしくおねがいします',
    cover: 'cover.jpg',
    image: 'user-12.png',
    location: '東京都',
    league: 'B',
    ranking: 12,
    score: 121,
    putt: 49,
    career: 1,
  },
];

export default samples;
